services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/gateway/.env
    environment:
      NODE_ENV: production
    depends_on:
      - auth-ms
    networks:
      - challenge-network

  auth-ms:
    container_name: auth-ms
    build:
      context: .
      dockerfile: apps/auth-ms/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - apps/auth-ms/.env
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - challenge-network

  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - challenge-network
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      POSTGRES_DB: jungle_gaming
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  challenge-network:
    driver: bridge
